import { ProductProps } from './entities/Product';

const BASE_PATH = process.env.NODE_ENV === 'production' ? '/tuttogusto' : '';

export const STATIC_CATEGORIES = [
  { id: 'cat-kitchen', name: 'Кухня и Горячие блюда', slug: 'kitchen', sortOrder: 1 },
  { id: 'cat-drinks', name: 'Авторский кофе и Напитки', slug: 'drinks', sortOrder: 2 },
  { id: 'cat-bakery', name: 'Свежая выпечка и Десерты', slug: 'bakery', sortOrder: 3 },
];

export const STATIC_PRODUCTS: ProductProps[] = [
  {
    id: 'prod-1',
    title: 'Паста Карбонара с гуанчиале',
    description: 'Классическая итальянская паста с подкопченным щекочеством, яичным желтком и сыром Пармезан.',
    price: 520,
    image: `${BASE_PATH}/assets/menu/kitchen/1-6.jpg`,
    type: 'DISH',
    weightVolume: '320г',
    prepTime: 20,
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-kitchen',
  },
  {
    id: 'prod-2',
    title: 'Стейк из лосося с соусом тар-тар',
    description: 'Нежное филе лосося на гриле, подается с паровым брокколи и цитрусовым соусом.',
    price: 890,
    image: `${BASE_PATH}/assets/menu/kitchen/1-7.jpg`,
    type: 'DISH',
    weightVolume: '280г',
    prepTime: 25,
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-kitchen',
  },
  {
    id: 'prod-3',
    title: 'Салат Цезарь с сочной креветкой',
    description: 'Хрустящий романо, тигровые креветки на гриле, соус из анчоусов и пармезановые чипсы.',
    price: 640,
    image: `${BASE_PATH}/assets/menu/kitchen/1-8.jpg`,
    type: 'DISH',
    weightVolume: '250г',
    prepTime: 15,
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-kitchen',
  },
  {
    id: 'prod-4',
    title: 'Том Ям с морепродуктами',
    description: 'Пряный тайский суп на кокосовом молоке с креветками, кальмаром и грибами цаогу.',
    price: 680,
    image: `${BASE_PATH}/assets/menu/kitchen/10.jpg`,
    type: 'DISH',
    weightVolume: '400мл',
    prepTime: 18,
    isAvailable: true,
    isFeatured: false,
    categoryId: 'cat-kitchen',
  },
  {
    id: 'prod-5',
    title: 'Сытный завтрак «Туттогусто»',
    description: 'Яйца пашот на бриоши, авокадо, слабосоленый лосось и свежий микс салатов.',
    price: 580,
    image: `${BASE_PATH}/assets/menu/kitchen/11.jpg`,
    type: 'DISH',
    weightVolume: '350г',
    prepTime: 15,
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-kitchen',
  },
  {
    id: 'prod-6',
    title: 'Ризотто с белыми грибами',
    description: 'Итальянский рис арборио, ароматизированный белым вином и трюфельным маслом.',
    price: 590,
    image: `${BASE_PATH}/assets/menu/kitchen/12.jpg`,
    type: 'DISH',
    weightVolume: '300г',
    prepTime: 22,
    isAvailable: true,
    isFeatured: false,
    categoryId: 'cat-kitchen',
  },
  {
    id: 'prod-7',
    title: 'Бургер с рваной говядиной и чеддером',
    description: 'Сочная томленая говядина, карамелизованный лук, фирменный соус барбекю и картофель фри.',
    price: 650,
    image: `${BASE_PATH}/assets/menu/kitchen/13.jpg`,
    type: 'DISH',
    weightVolume: '420г',
    prepTime: 20,
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-kitchen',
  },
  {
    id: 'prod-8',
    title: 'Раф Кедровый Иркутский',
    description: 'Фирменный напиток с натуральным кедровым сиропом и дробленым орехом.',
    price: 360,
    image: `${BASE_PATH}/assets/menu/drinks/36.jpg`,
    type: 'DRINK',
    weightVolume: '350мл',
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-drinks',
  },
  {
    id: 'prod-9',
    title: 'Капучино Овсяный salted caramel',
    description: 'Классический двойной эспрессо на овсяном молоке с добавлением соленой карамели.',
    price: 320,
    image: `${BASE_PATH}/assets/menu/drinks/37.jpg`,
    type: 'DRINK',
    weightVolume: '300мл',
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-drinks',
  },
  {
    id: 'prod-10',
    title: 'Латте Малина-Фисташка',
    description: 'Нежный кофейный напиток с натуральным пюре малины и фисташковой пастой.',
    price: 380,
    image: `${BASE_PATH}/assets/menu/drinks/38.jpg`,
    type: 'DRINK',
    weightVolume: '400мл',
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-drinks',
  },
  {
    id: 'prod-11',
    title: 'Миндальный круассан',
    description: 'Французский хрустящий круассан с щедрой начинкой из франжипана и лепестками миндаля.',
    price: 280,
    image: `${BASE_PATH}/assets/menu/bakery/25.jpg`,
    type: 'BAKERY',
    weightVolume: '140г',
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-bakery',
  },
  {
    id: 'prod-12',
    title: 'Чизкейк Сан-Себастьян',
    description: 'Нежнейший обожженный баскский чизкейк с карамельной корочкой и ягодным кули.',
    price: 390,
    image: `${BASE_PATH}/assets/menu/bakery/26.jpg`,
    type: 'BAKERY',
    weightVolume: '180г',
    isAvailable: true,
    isFeatured: true,
    categoryId: 'cat-bakery',
  },
];

export const STATIC_NEWS = [
  {
    id: 'news-1',
    title: 'Новое сезонное меню осенне-зимних напитков в Иркутске!',
    content: 'Согрейтесь авторскими напитками с кедровым орехом, облепихой и пряной корицей. Ждем вас в гости!',
    image: `${BASE_PATH}/assets/menu/slider/slide-2.jpg`,
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'news-2',
    title: 'Завтраки весь день по выходным',
    content: 'Каждую субботу и воскресенье готовим наши знаменитые бриоши с лососем и яйцами пашот без ограничений по времени!',
    image: `${BASE_PATH}/assets/menu/slider/slide-3.jpg`,
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
];
